'use strict'; // code generated by pbf v3.2.1

// PUFEntry ========================================

var PUFEntry = self.PUFEntry = {};

PUFEntry.read = function (pbf, end) {
    return pbf.readFields(PUFEntry._readField, {caname: "", manu: "", ts: null, pufid: null, comrp: null, tag: null}, end);
};
PUFEntry._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.caname = pbf.readString();
    else if (tag === 2) obj.manu = pbf.readString();
    else if (tag === 3) obj.ts = pbf.readBytes();
    else if (tag === 4) obj.pufid = pbf.readBytes();
    else if (tag === 5) obj.comrp = pbf.readBytes();
    else if (tag === 6) obj.tag = pbf.readBytes();
};
PUFEntry.write = function (obj, pbf) {
    if (obj.caname) pbf.writeStringField(1, obj.caname);
    if (obj.manu) pbf.writeStringField(2, obj.manu);
    if (obj.ts) pbf.writeBytesField(3, obj.ts);
    if (obj.pufid) pbf.writeBytesField(4, obj.pufid);
    if (obj.comrp) pbf.writeBytesField(5, obj.comrp);
    if (obj.tag) pbf.writeBytesField(6, obj.tag);
};

exports.PUFEntry = PUFEntry;